version: "3"
services:
  mongo:
    image: "mongo:4.0.5"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "myuser"
      MONGO_INITDB_ROOT_PASSWORD: "mypass"
      MONGO_INITDB_DATABASE: "sequencing"
    ports:
      - "27017:27017"
  api:
    depends_on:
      - mongo
    build: "./api"
    command: bash -c "pipenv install && pipenv run flask run -h 0.0.0.0"
    volumes:
      - "./api/:/code/"
    ports:
      - "5000:5000"
  interface:
    depends_on:
      - api
    build: "./interface"
    command: bash -c "yarn install && yarn start"
    volumes:
      - "./interface/:/code/"
    ports:
      - "3000:3000"
