version: "3"
services:
  mongo:
    image: "mongo:4.0.5"
    environment:
      MONGO_INITDB_ROOT_USERNAME: "myuser"
      MONGO_INITDB_ROOT_PASSWORD: "mypass"
      MONGO_INITDB_DATABASE: "sequencing"
    ports:
      - "27017:27017"
  api:
    build: "./api"
    network_mode: "host"
    command: bash -c "pipenv install && pipenv run flask run -h 0.0.0.0"
    volumes:
      - "./api/:/code/"
    ports:
      - "5000:5000"
  interface:
    build: "./old-interface"
    command: "npm run start"
    volumes:
      - "./old-interface/:/code/"
    ports:
      - "3000:3000"
