version: "3"
services:
  db:
    image: "postgres:latest"
    environment:
      POSTGRES_USER: "myuser"
      POSTGRES_PASSWORD: "mypass"
      POSTGRES_DB: "sequencing"
    ports:
      - "5432:5432"
  api:
    build: "./api"
    command: "pipenv run flask run -h 0.0.0.0"
    volumes:
      - ./api/:/code/
    ports:
      - "5000:5000"
  interface:
    build: "./interface"
    command: "npm run start"
    volumes:
      - ./interface/:/code/
    ports:
      - "3000:3000"
