export const NETWORK_STATUS = {
  REQUEST: "REQUEST",
  SUCCESS: "SUCCESS",
  FAILURE: "FAILURE"
};

export default {
  UPLOAD_DATASET: "UPLOAD_DATASET",
  DELETE_DATASET: "DELETE_DATASET",
  CLEAR_QUERY: "CLEAR_QUERY",

  LOAD_DATASETS: "LOAD_DATASETS",
  LOAD_QUERY: "LOAD_QUERY",

  LOAD_DATASET_SEQUENCES: "LOAD_DATASET_SEQUENCES",
  LOAD_QUERY_MATCHES: "LOAD_QUERY_MATCHES",

  SET_ACTIVE: "SET_ACTIVE"
};
