"""empty message

Revision ID: 5528eacaa6a0
Revises: 687d42277b80
Create Date: 2019-01-20 16:21:24.052422

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "5528eacaa6a0"
down_revision = "687d42277b80"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("my_table", "user_filename2")
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "my_table",
        sa.Column("user_filename2", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
