"""empty message

Revision ID: 687d42277b80
Revises: 2f47f69b2839
Create Date: 2019-01-20 16:21:15.290462

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "687d42277b80"
down_revision = "2f47f69b2839"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("my_table", sa.Column("user_filename2", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("my_table", "user_filename2")
    # ### end Alembic commands ###
